### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by msecret** [18F/18F-stylelint#5]
OK I've researched and thought about this now. Here's what I think:
- We should rename the package so it's scoped to the 18F org, so it would be named:

```
@18f/stylelint
```

I think this is a better patter then `18F-` because it uses an npm supported convention. This repo would still be called what it is now
- We should [scope the package to the 18f npm org somehow](https://docs.npmjs.com/orgs/scoping-packages). This would probably mean:
  - Logging into npm `npm login`
  - Getting `team-admin` role added to your account on the 18f npm org.
  - Scoping the package to the 18f org, `npm init --scope=18f` . This might require removing the initial package.json and then re-doing it.
- [Setting roles and permissions so 18F team members can write to the package](https://docs.npmjs.com/orgs/package-access).
  - `npm access grant read-write 18f:developers @18f/stylelint`
  - Add some people as owners: `npm owner add <user> @18f/stylelint` where user is [msecret, 18f-devops]. 

Something I'm still unclear on: I think the `npm init --scope=18f` will add the rename the package in the package.json, so step 1 may not be required at all, it might be best to start with that part.

**Comment by el-mapache** [comment]
@msecret I think it might be better to rename the npm package `stylelint-config`, `stylelint-rules` or something similar, to avoid confusion between our package and the actual stylelint project. What is your take?

**Comment by msecret** [comment]
@el-mapache that sounds fine to me. I think `stylelint-rules` sounds good.

**Comment by el-mapache** [comment]
Closing this as it's been resolved and published
