### ISSUE TITLE
Stylus support

### ISSUE THREAD

**Issue by glebmachine** [18F/18F-stylelint#6]
Hi!
Do you have plans to add stylus support?)

**Comment by jeddy3** [comment]
This is an [upstream issue](https://github.com/stylelint/stylelint/issues/674) in stylelint that relies on someone contributing a `postcss-stylus` parser to the community, which is no trivial task I'm afraid. If you'd like to contribute this parser, then I suggest checking out the existing parsers for inspiration: `postcss-scss`, `postcss-less`, `postcss-safe-parser` and `sugarss`.
